### ISSUE TITLE
实验指导书

### ISSUE THREAD

**Issue by Allenyhf** [mansicer/NJU-OSlab-2019#1]
请问有实验指导书或者实验环境搭建教程吗

**Comment by mansicer** [comment]
http://114.212.80.195:8170/
实验环境是Linux系统（我用的是Ubuntu 18）和 qemu 模拟器。
2019年的实验网站，仅校内访问，但是好像现在已经挂掉了。
2020年的实验说明可能可以在相关老师的主页找到。
如果你是外校同学想要学习OS的话，可以在B站搜索蒋炎岩老师的操作系统课程，如果你对项目感兴趣，可以查看ICS课程的PA项目，指导书非常详细。

**Comment by Allenyhf** [comment]
非常感谢，PA最近正在做，b站的课程也在跟进。但是，发现老师好像并不开源lab，很遗憾。还有PA和oslab好像不一样吧？PA是完善一个虚拟机项目，oslab应该是写OS吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sicer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 晚上6:49
收件人:&nbsp;"mansicer/NJU-OSlab-2019"<NJU-OSlab-2019@noreply.github.com&gt;;
抄送:&nbsp;"Valencia Zada"<1347208009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mansicer/NJU-OSlab-2019] 实验指导书 (#1)





 
http://114.212.80.195:8170/
 实验环境是Linux系统（我用的是Ubuntu 18）和 qemu 模拟器。
 2019年的实验网站，仅校内访问，但是好像现在已经挂掉了。
 2020年的实验说明可能可以在相关老师的主页找到。
 如果你是外校同学想要学习OS的话，可以在B站搜索蒋炎岩老师的操作系统课程，如果你对项目感兴趣，可以查看ICS课程的PA项目，指导书非常详细。

**Comment by mansicer** [comment]
看了一下老师的主页，lab确实不是开源的，我也没有办法向外提供资源，抱歉。
PA和OSlab的区别大致如你所说，两者面向的层面有一定区别，但是计算机系统相关的知识是相通的，PA的代码中也包含一个简单操作系统，你可以参考其中的实现，许多部分其实是写的比OSlab好的，但关于线程，信号量等内容没有涉及到。OSlab的每次实验间是相对独立的，而且部分代码是由助教维护的，可能在框架上没有那么易懂。
PA中也有些部分是OSlab没有涉及到的，如果你对IO驱动方面的内容感兴趣，可以多看看PA的实现。

**Comment by Allenyhf** [comment]
好的，谢谢你的建议，实在是太感谢了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sicer"<notifications@github.com&gt;; 
发送时间: 2020年6月4日(星期四) 晚上7:26
收件人: "mansicer/NJU-OSlab-2019"<NJU-OSlab-2019@noreply.github.com&gt;; 
抄送: "Valencia Zada"<1347208009@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mansicer/NJU-OSlab-2019] 实验指导书 (#1)





 
看了一下老师的主页，lab确实不是开源的，我也没有办法向外提供资源，抱歉。
 PA和OSlab的区别大致如你所说，两者面向的层面有一定区别，但是计算机系统相关的知识是相通的，PA的代码中也包含一个简单操作系统，你可以参考其中的实现，许多部分其实是写的比OSlab好的，但关于线程，信号量等内容没有涉及到。OSlab的每次实验间是相对独立的，而且部分代码是由助教维护的，可能在框架上没有那么易懂。
 PA中也有些部分是OSlab没有涉及到的，如果你对IO驱动方面的内容感兴趣，可以多看看PA的实现。
